import tkinter as tk
window = tk.Tk()
window.title('Калькулятор')
window.geometry('350x350')
window.resizable(False,False)
button_add = tk.Button(window, text = '+')
button_add.place(x = 120, y = 200, width = 30, height =30 )
button_min = tk.Button(window, text = '-')
button_min.place(x = 150, y = 200, width = 30, height =30)
button_dim = tk.Button(window, text = '/')
button_dim.place(x = 180, y = 200, width = 30, height = 30)
button_mul = tk.Button(window, text = '* ')
button_mul.place(x = 210, y = 200, width = 30, height = 30)
number1_entry = tk.Entry()
number1_entry.place(x = 80, y = 60, width = 200, height= 40) 
number2_entry = tk.Entry()
number2_entry.place(x = 80, y = 140, width = 200, height= 40) 
answer_entry = tk.Entry()
answer_entry.place(x = 80, y = 260, width = 200, height= 40)
number1 = tk.Label(window, text='Введите первое число:')
number1.place(x=80, y = 36)
number2 = tk.Label(window, text='Введите второе число:')
number2.place(x=80, y = 116)
answer = tk.Label(window, text='Ответ:')
answer.place(x = 80, y = 236)

window.mainloop()

